---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

verifier:
  name: inspec

platforms:
  - name: win2012r2
    driver_config:
      box: opentable/win-2012r2-standard-amd64-nocm
  - name: centos7
    driver:
      box: bento/centos-7.2

suites:
  - name: default
