---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 13

verifier:
  name: inspec

platforms:
  - name: win2012r2
    driver_config:
      box: opentable/win-2012r2-standard-amd64-nocm
    provisioner:
      require_chef_omnibus: 13
  - name: centos7

suites:
  - name: default
