---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 17
  install_strategy: upgrade # once, upgrade
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: win2012r2
    driver_config:
      box: mwrock/Windows2012R2
  - name: centos7
    driver:
      box: bento/centos-7.2

suites:
  - name: default
