name 'zipr'
maintainer 'Alex Munoz'
maintainer_email 'amunoz951@gmail.com'
license 'Apache-2.0'
description 'Provides idempotent compression and extraction resources'
long_description 'Provides idempotent compression and extraction resources'
source_url 'https://github.com/amunoz951/zipr'
issues_url 'https://github.com/amunoz951/zipr/issues'
chef_version '>= 12'
version '2.0.4'

supports 'windows'
supports 'centos'

depends 'build-essential'
