name 'zipr_test'
maintainer 'Alex Munoz'
maintainer_email 'amunoz951@gmail.com'
license 'Apache-2.0'
description 'Tests zipr cookbook'
version '0.2.0'
source_url 'https://github.com/amunoz951/zipr'
issues_url 'https://github.com/amunoz951/zipr/issues'
chef_version '>= 12'

depends 'zipr'
